### ISSUE TITLE
URGENT: if eligible screen text updates 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#141] opened 2020-05-12 19:23 UTC
![Screen Shot 2020-05-12 at 12 24 16 PM](https://user-images.githubusercontent.com/64874011/81736484-813df200-944b-11ea-8525-f3e267597e57.png)

Text updates:
1.We could use your help! ---> Getting Started
2. We are looking to build our community in New York first. Looks like you fit the bill. Now, let’s get you set up. ----->To access the consent and surveys, you will need to create an account.  
You will use your email or phone number to log into your account in the future.

3. Submit button. ---> Create account

4. Let's try to match the mockup UI

**Comment by jay-hodgson** [comment] 2020-05-13 01:20
I shouldn't assign urgent issues to myself if I can't work on them in the next day.

**Comment by conundrumgirl** [comment] 2020-05-13 17:46
Duplicate of #154

**Closed by conundrumgirl** 2020-05-13 17:46 UTC
