### ISSUE TITLE
Consent: Screen 8: Will I receive any form of compensation for participating in the study?

### ISSUE THREAD

**Issue by vbarone00** [Sage-Bionetworks/covidrecoverycorps#633] opened 2020-07-22 23:53 UTC
NEW Copy: [Summary]
You will be given a $50 gift card if you complete all of the surveys and provide biosamples in
person. If you complete all your surveys and provide a biosample with an at-home kit will receive a $20 gift card.

You will not receive any profit from this or future research.

NEW Copy: [Full Text]
You will be given a $50 gift card if you complete all of the surveys and provide biosamples in
person. If you complete all your surveys and provide a biosample with an at-home kit will receive a $20 gift card.

Researchers will use your data to make discoveries. If any of their studies lead to new tests, drugs, or other commercial products, you will not get any profits. These inventions will be the property of the researchers who develop them.

**Comment by vbarone00** [comment] 2020-07-22 23:54
@flylikeabirdfloatlikeabuoy This is new screen in the e-consent flow so I Alina would need design  and visual

**Comment by conundrumgirl** [comment] 2020-07-23 17:00
duplicate of https://github.com/Sage-Bionetworks/covidrecoverycorps/issues/574
done

**Closed by conundrumgirl** 2020-07-23 17:00 UTC
