### ISSUE TITLE
Dashboard: follow up notification settings if they have opted out of testing

### ISSUE THREAD

**Issue by conundrumgirl** [Sage-Bionetworks/covidrecoverycorps#623] opened 2020-07-15 19:31 UTC
https://github.com/Sage-Bionetworks/covidrecoverycorps/issues/614
1. Notification subscription and 'invite a friend' if they picked 'no testing'

**f they opted out of testing, we wrap up their journey:**

[Thank you celebratory cone icon]
[Header] 
Thank you for your contribution to the COVID Recovery Corps Study! 

[Body]
As we learn more, we will provide updates on the results of the study in newsletters, online presentations, and community meetings.  

[Followup notification settings]
Would you like to receive email updates on the this study and other related-studies? 

No thank you [Toggle] Yes, please email me updates on study findings

[Invite a friend to join the study]
<img width="406" alt="Screen Shot 2020-07-13 at 2 38 01 PM" src="https://user-images.githubusercontent.com/64874011/87356165-74568100-c516-11ea-8353-d07f28458605.png">

2. If they have scheduled appointment and missed the apointment date
If their appointment date has passed and their was no interaction with the lab system, we need to infer that they missed their appointment so we would show this screen - please check with @alxdarksage 

<img width="558" alt="Screen Shot 2020-07-13 at 2 55 42 PM" src="https://user-images.githubusercontent.com/64874011/87357466-ee880500-c518-11ea-9fa9-5fd44515c10c.png">

**Comment by conundrumgirl** [comment] 2020-07-15 19:33
@flylikeabirdfloatlikeabuoy - v2 dashboard stuff

**Comment by mkellen** [comment] 2020-08-11 18:07
Part 2 of this is duplicate of #626

**Comment by flylikeabirdfloatlikeabuoy** [comment] 2020-08-11 18:56
@conundrumgirl  For those who have canceled or missed appointment, please reference:
<img width="246" alt="Screen Shot 2020-08-11 at 11 56 33 AM" src="https://user-images.githubusercontent.com/64874011/89937274-b59b8880-dbc9-11ea-9c05-29c375a39c49.png">


<img width="974" alt="Screen Shot 2020-08-11 at 11 56 10 AM" src="https://user-images.githubusercontent.com/64874011/89937229-a74d6c80-dbc9-11ea-8d9b-37f7d2af1b34.png">

**Comment by flylikeabirdfloatlikeabuoy** [comment] 2020-08-11 18:57
@conundrumgirl  For those who are not interested in testing - their followup experience ends and they won't be receiving any return of result.  
I've removed the subscription :

<img width="849" alt="Screen Shot 2020-08-11 at 11 57 04 AM" src="https://user-images.githubusercontent.com/64874011/89937319-c815c200-dbc9-11ea-88a2-bac4be283350.png">

**Closed** 2020-08-18 17:21 UTC
Labels: needs verification
